app:
  api:
    settings:
      cross-origin:
        urls: http://localhost:4200


spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mysql://localhost:3306/db_mapersive
    username: root
    password:
  jpa:
    generate-ddl: true
    hibernate:
      show-sql: true
      ddl-auto: create
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
